name: Design Doc Reviewer build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12.0'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Install python libraries and packages required
        run: pip install -r requirements.txt
      - name: Clone cmake-example for testing
        run: git clone https://github.com/gokhanettin/cmake-example.git
      - name: Run python scripts
        run: python test/test.py cmake-example/apps/app1.cc
